%% Analyzing impulse-response (NN)
iSel = ':'; % 1:50; % ':';

% Solve an Input-Output Fitting problem with a Neural Network
% Script generated by NFTOOL
dataset = load('../Transforms/mat/CaseStudy_Real_Rain_Data.mat');
t = dataset.t;
inputs = dataset.fluxIn;
targets = -dataset.fluxOut;

% Create a Fitting Network
hiddenLayerSize = [30, 30, 30];
net = fitnet(hiddenLayerSize);

%     % Set up Division of Data for Training, Validation, Testing
%     net.divideParam.trainRatio = 70/100;
%     net.divideParam.valRatio = 15/100;
%     net.divideParam.testRatio = 15/100;

% Train the Network
[net, ~] = train(net, inputs(:, iSel), targets(:, iSel));

% Test the Network
outputs = net(inputs);
%     errors = gsubtract(outputs, targets);
%     performance = perform(net, targets, outputs);

figure();
plot(t, targets, 'g');
hold on
plot(t, outputs, 'r');
hold off
%% END NN